name: sunyo26s
channels:
- conda-forge
dependencies:
- cartopy
- ffmpeg
- geopandas
- h5py
- ipykernel
- ipywidgets
- jupyter
- jupyter-book
- jupyterlab
- jupyterlab-myst
- matplotlib
- metpy
- mystmd
- nb_conda_kernels
- nbconvert>=4.1
- netcdf4
- nodejs
- nomkl
- notebook
- numpy
- owslib
- pandas
- pint
- pip
- pyarrow
- pytest
- python-awips
- python<3.13
- scikit-learn
- scipy
- seaborn
- shapely
- siphon
- six
- sphinx>=1.3
- sphinx_rtd_theme
- urllib3
- voila
- xarray
- xgboost
