name: unidata-standard
channels:
  - rttools
  - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - pandas
  - scipy
  - metpy
  - xarray
  - scikit-learn
  - cartopy
  - seaborn
  - netcdf4
  - pyorbital
  - pytz
  - siphon
  - statsmodels
  - pip
  - cfgrib
  - climlab
  - climlab-rrtmg
  - typhon
  - ipympl
  - pint-xarray
  - pyarts
  - ultraplot
  - miepython
  - wrf-python
variables:
  ARTS_DATA_PATH: /share/ESCI345/arts-data/arts-cat-data-2.6.12/
  ARTS_XML_ATMO: /share/ESCI345/arts-data/arts-xml-data-2.6.12/
